spring:
  application:
    name: dqnetmusic # 应用名称
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # 数据库驱动：
    name: defaultDataSource   # 数据源名称
    url: jdbc:mysql://localhost:3306/db_dqnetmusic?serverTimezone=UTC # 数据库连接地址
    # 数据库用户名&密码：
    username: root
    password: 123123
  jackson:
    # 全局设置@JsonFormat的格式pattern
    date-format: yyyy-MM-dd HH:mm:ss
    # 当地时区
    locale: zh
    # 设置全局时区
    time-zone: GMT+8
  # sa-token配置
  sa-token:
    # token名称 (同时也是cookie名称)
    token-name: satoken
    # token有效期，单位s 默认30天, -1代表永不过期
    timeout: 2592000
    # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
    activity-timeout: -1
    # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
    allow-concurrent-login: false
    # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
    is-share: false
    # token风格
    token-style: uuid
  # 用户写死, 不通过 Security 来鉴权
  security:
    user:
      name: blade
      password: 123
# mybatis-plus
mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb_ # 表格前缀

server:
  port: 8080 # 应用服务 WEB 访问端口
  servlet:
    context-path: /api
